apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jxe1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jxe1
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jxe1
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jxe1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jxe1
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-sfew-tenant/rhtap-demo-app/hacbs-test-project-jxe1@sha256:b59b0fe62149e867b8889966276077508fd1e951f7a83a11ce017fb654a8a47e
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
